# Generated by Django 4.0.3 on 2022-04-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonteachingleavebalance',
            name='e_id',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='NonTeachingLeaveBalance',
        ),
    ]
