# Generated by Django 4.0.3 on 2022-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_remove_nonteachingleavebalance_e_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
