# Generated by Django 4.0.3 on 2022-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonteachingleave',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
