# Generated by Django 4.0.4 on 2022-05-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_rename_orginization_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('s_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strength', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lecturer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organization')),
            ],
        ),
    ]
