# Generated by Django 4.0.3 on 2022-04-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavebalance',
            old_name='Allocated_Days',
            new_name='allocated_days',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='Available_Days',
            new_name='available_days',
        ),
        migrations.RenameField(
            model_name='leavebalance',
            old_name='Leave_Type',
            new_name='leave_type',
        ),
    ]
