# Generated by Django 4.0.3 on 2022-03-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='null', max_length=40),
            preserve_default=False,
        ),
    ]
