# Generated by Django 4.0.3 on 2022-03-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_student_nationality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
