# Generated by Django 4.0.3 on 2022-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('u_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('profile_pic', models.ImageField(upload_to='base/templates/')),
                ('mobile', models.BigIntegerField()),
                ('blood', models.CharField(max_length=5)),
                ('parent_mobile', models.BigIntegerField()),
                ('parent_name', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=40)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
