# Generated by Django 4.0.3 on 2022-04-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_leave_type_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='nonteachingleave',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='nonteachingleavebalance',
            name='e_id',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='NonTeachingLeave',
        ),
        migrations.DeleteModel(
            name='NonTeachingLeaveBalance',
        ),
    ]
