# Generated by Django 4.0.3 on 2022-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orginization_email_alter_student_orginization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
