# Generated by Django 4.0.3 on 2022-05-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orginization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='orginization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.orginization'),
        ),
    ]
