# Generated by Django 4.0.3 on 2022-04-29 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_delete_faculty_delete_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orginization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginization_name', models.CharField(max_length=200, unique=True)),
                ('owner_email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('u_id', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='base/templates/')),
                ('mobile', models.BigIntegerField()),
                ('blood', models.CharField(max_length=5)),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_mobile', models.BigIntegerField()),
                ('relation', models.CharField(max_length=200)),
                ('cast', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=40)),
                ('admission_date', models.DateField()),
                ('orginization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orginization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='orginization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.orginization'),
            preserve_default=False,
        ),
    ]
