# Generated by Django 4.0.4 on 2022-05-08 14:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_alter_student_orginization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orginization',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='nonteaching',
            old_name='orginization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='orginization_name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='orginization',
            new_name='organization',
        ),
    ]
