# Generated by Django 4.0.3 on 2022-04-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_user_orginization_lecturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginization',
            old_name='owner_email',
            new_name='owner',
        ),
    ]
