# Generated by Django 4.0.3 on 2022-04-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_student_user_orginization_lecturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='u_id',
            new_name='e_id',
        ),
        migrations.RenameField(
            model_name='orginization',
            old_name='owner_email',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='course',
            name='orginization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.orginization'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orginization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orginization')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.branch', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.branch', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.branch', unique=True),
            preserve_default=False,
        ),
    ]
