# Generated by Django 4.0.3 on 2022-04-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_owner_email_orginization_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='u_id',
            new_name='e_id',
        ),
    ]
