# Generated by Django 4.0.4 on 2022-05-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_orginization_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=20),
        ),
    ]
