# Generated by Django 4.0.4 on 2022-05-08 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0004_alter_nonteachingleave_id'),
        ('registration', '0001_initial'),
        ('base', '0010_alter_course_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecturer',
            new_name='Faculty',
        ),
    ]
